# Pipeline to run on pushes to release candidate branches PRs to such branches

# NOTE: It is assumed that all release candidate branches match the pattern 'rc-**'

name: ci-rc
run-name: ci-rc
on:
  workflow_dispatch:
  push:
    branches: ["rc-**"]

jobs:
  tag-release:
    uses: ./.github/workflows/tag-release.yml
